// packages/cubejs-playground/src/scaffolding/react/App.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import { withRouter } from "react-router";
import "antd/dist/antd.css";
import "./index.css";
import { Layout, Menu } from "antd";

const AppLayout = ({ location, children }) => (
  <Layout style={{ height: '100%' }}>
    <Layout.Header style={{ padding: '0 32px' }}>
      <div
        style={{
          float: "left"
        }}
      >
        <h2
          style={{
            color: "#fff",
            margin: 0,
            marginRight: "1em",
            display: 'inline',
            width: 100,
            lineHeight: "54px"
          }}
        >
          My Dashboard
        </h2>
      </div>
      <Menu
        theme="dark"
        mode="horizontal"
        selectedKeys={[location.pathname]}
        style={{
          lineHeight: "64px"
        }}
      >
        <Menu.Item key="/explore">
          <Link to="/explore">Explore</Link>
        </Menu.Item>
        <Menu.Item key="/">
          <Link to="/">Dashboard</Link>
        </Menu.Item>
      </Menu>
    </Layout.Header>
    <Layout.Content
      style={{
        padding: "0 25px 25px 25px",
        margin: "25px"
      }}
    >
      {children}
    </Layout.Content>
  </Layout>
);

const cubejsApi = undefined;

const App = withRouter(({ location, children }) => (
  <AppLayout location={location}>
    {children.map(c => React.cloneElement(c, {
      cubejsApi
    }))}
  </AppLayout>
));

export default App;

// packages/cubejs-server-core/dev/templates/packages/vue-antd-static/template/template/src/App.vue
<template>
    <div>
        <a-layout-header class="header">

            <h2 style="color: rgb(255, 255, 255); margin: 0px 1em 0px 0px; display: inline; width: 200px; line-height: 54px;float: left">
                My Dashboard</h2>

          <a-menu
                  theme="dark"
                  mode="horizontal"
                  :default-selected-keys="['1']"
                  style="float: left"
                  :style="{ lineHeight: '64px' }"
          >
            <a-menu-item key="1" @click="key=1">
              ExplorePage
            </a-menu-item>
            <a-menu-item key="2" @click="key=2">
              DashboardPage
            </a-menu-item>

          </a-menu>


        </a-layout-header>


      <ExplorePage v-show="key==1"></ExplorePage>
      <DashboardPage v-show="key==2"></DashboardPage>


    </div>
</template>
<script>

    import DashboardPage from "~/components/DashboardPage";
    import ExplorePage from "~/components/ExplorePage";

    export default {
        components: {ExplorePage, DashboardPage},
        data() {
            return {
              key:1,
            };
        },
        methods: {
            callback(key) {
                console.log(key);
            },
        },
    };
</script>
