// examples/react-pivot-table/dashboard-app/src/components/QueryBuilder/FilterGroup.js
import React from 'react';
import * as PropTypes from 'prop-types';
import { Select } from 'antd';
import { Icon } from '@ant-design/compatible';
import MemberDropdown from './MemberDropdown';
import RemoveButtonGroup from './RemoveButtonGroup';
import FilterInput from './FilterInput';

const FilterGroup = ({
  members,
  availableMembers,
  addMemberName,
  updateMethods,
}) => (
  <span>
    {members.map((m) => (
      <div
        style={{
          marginBottom: 12,
        }}
        key={m.index}
      >
        <RemoveButtonGroup onRemoveClick={() => updateMethods.remove(m)}>
          <MemberDropdown
            onClick={(updateWith) =>
              updateMethods.update(m, { ...m, dimension: updateWith })
            }
            availableMembers={availableMembers}
            style={{
              width: 150,
              textOverflow: 'ellipsis',
              overflow: 'hidden',
            }}
          >
            {m.dimension.title}
          </MemberDropdown>
        </RemoveButtonGroup>
        <Select
          value={m.operator}
          onChange={(operator) => updateMethods.update(m, { ...m, operator })}
          style={{
            width: 200,
            marginRight: 8,
          }}
        >
          {m.operators.map((operator) => (
            <Select.Option key={operator.name} value={operator.name}>
              {operator.title}
            </Select.Option>
          ))}
        </Select>
        <FilterInput
          member={m}
          key="filterInput"
          updateMethods={updateMethods}
        />
      </div>
    ))}
    <MemberDropdown
      onClick={(m) =>
        updateMethods.add({
          dimension: m,
        })
      }
      availableMembers={availableMembers}
      type="dashed"
      icon={<Icon type="plus" />}
    >
      {addMemberName}
    </MemberDropdown>
  </span>
);

FilterGroup.propTypes = {
  members: PropTypes.array.isRequired,
  availableMembers: PropTypes.array.isRequired,
  addMemberName: PropTypes.string.isRequired,
  updateMethods: PropTypes.object.isRequired,
};
export default FilterGroup;

// packages/cubejs-server-core/dev/templates/packages/vue-antd-static/template/template/src/components/cube/QueryBuilder/FilterGroup.vue
<template>
    <div>
    <span :key=index
          v-for="(m,index) in membersProp">

        <RemoveButtonGroup
                @onRemoveClick="()=>{remove(m)}"
        >
          <MemberDropdown
                  :availableMembersProp=availableMembersProp
                  @updateMethodsAdd="(updateWith)=>updateDateRange(m,{...m,dimension: updateWith})"
          >
            {{m.member.title}}
    </MemberDropdown>
    </RemoveButtonGroup>
      <ASelect
              @change="(operator) => updateDateRange(m, { ...m, operator })"
              style="width: 200px;margin-right: 8px"
              :value="m.operator">
        <a-select-option v-for="operator in m.operators" :key="operator.name" :value="operator.name">
            {{ operator.title }}
       </a-select-option>

      </ASelect>
      <FilterInput v-model="m.values" @change="(values)=>{
        updateDateRange(m,{...m,values: values})
      }">
      </FilterInput>
  </span>
        <span>
      <a-button>
          <MemberDropdown
                  :available-members-prop="availableMembersProp"
                  @updateMethodsAdd="add"
          >
          {{addMemberNameProp}}
      </MemberDropdown>
      </a-button>

    </span>
    </div>
</template>

<script>

    import RemoveButtonGroup from "~/components/cube/QueryBuilder/RemoveButtonGroup";
    import MemberDropdown from "~/components/cube/QueryBuilder/MemberDropdown";
    import FilterInput from "~/components/cube/QueryBuilder/FilterInput";

    export default {
        name: "FilterGroup",
        layout: 'empty',
        auth: 'false',
        components: {FilterInput, MemberDropdown, RemoveButtonGroup},
        props: {
            itemProp: {
                type: Object,
                require: false,
                default: () => {
                }
            },
            list: {
                type: Array,
                require: false,
                default: () => []
            },
            membersProp: {
                type: Array,
                require: false,
                default: () => []
            },
            availableMembersProp: {
                type: Array,
                require: false,
                default: () => []
            },
            addMemberNameProp: {
                type: String,
                require: false,
                default: () => ""
            },
            updateMethods: {
                type: Object,
                require: false,
                default: () => {
                }
            },
        },
        data() {

            return {
                title: "demo",
                item: "",
                DateRanges: [
                    {
                        title: "All time",
                        value: undefined
                    },
                    {
                        value: "Today"
                    },
                    {
                        value: "Yesterday"
                    },
                    {
                        value: "This week"
                    },
                    {
                        value: "This month"
                    },
                    {
                        value: "This quarter"
                    },
                    {
                        value: "This year"
                    },
                    {
                        value: "Last 7 days"
                    },
                    {
                        value: "Last 30 days"
                    },
                    {
                        value: "Last week"
                    },
                    {
                        value: "Last month"
                    },
                    {
                        value: "Last quarter"
                    },
                    {
                        value: "Last year"
                    }
                ],
            }
        },
        computed: {
            currentIndex() {
                return ''
            }
        },

        watch: {
            "title"() {
            },
            "itemProp": {
                immediate: true,
                handler(val) {
                    if (val) {
                        this.item = this.$common.deepCopy(val)

                    }
                }
            },
        },

        async mounted() {

        },
        methods: {
            remove(m) {
                this.updateMethods["remove" + this.addMemberNameProp + "s"](m.dimension)
            },
            updateDateRange(oldM, newM) {
                this.updateMethods["update" + this.addMemberNameProp + "s"](oldM, newM)

            },

            add(m) {
                const data = {
                    dimension: m.name
                };
                this.updateMethods["add" + this.addMemberNameProp + "s"](data)
            },
            async asyncMounted() {


            },
            async methodDemo() {

            },
            async dispatch() {
                this.$store.dispatch('modules/common/setCurrentIndex', 1)
            },
        }
    }
</script>

<style lang='scss'>

</style>
