// packages/cubejs-playground/src/scaffolding/react/QueryBuilder/MemberGroup.js
import React from 'react';
import * as PropTypes from 'prop-types';
import MemberDropdown from './MemberDropdown';
import RemoveButtonGroup from './RemoveButtonGroup';

const MemberGroup = ({
  members, availableMembers, addMemberName, updateMethods
}) => (
  <span>
    {members.map(m => (
      <RemoveButtonGroup key={m.index || m.name} onRemoveClick={() => updateMethods.remove(m)}>
        <MemberDropdown availableMembers={availableMembers} onClick={updateWith => updateMethods.update(m, updateWith)}>
          {m.title}
        </MemberDropdown>
      </RemoveButtonGroup>
    ))}
    <MemberDropdown onClick={m => updateMethods.add(m)} availableMembers={availableMembers} type="dashed" icon="plus">
      {addMemberName}
    </MemberDropdown>
  </span>
);

MemberGroup.propTypes = {
  members: PropTypes.array.isRequired,
  availableMembers: PropTypes.array.isRequired,
  addMemberName: PropTypes.string.isRequired,
  updateMethods: PropTypes.object.isRequired
};

export default MemberGroup;

// packages/cubejs-server-core/dev/templates/packages/vue-antd-static/template/template/src/components/cube/QueryBuilder/MemberGroup.vue
<template>
  <span>
    <span :key=index
          v-for="(m,index) in membersProp">
      <RemoveButtonGroup
        @onRemoveClick="()=>{remove(m)}"
      >
        <MemberDropdown
          :availableMembersProp=availableMembersProp
          @updateMethodsAdd="(newM)=>update(m,newM)"
        >
          {{m.title}}
    </MemberDropdown>
    </RemoveButtonGroup>
  </span>

    <a-button>
    <MemberDropdown
      :available-members-prop="availableMembersProp"
      type="dashed"
      @updateMethodsAdd="add"
    >
      {{addMemberNameProp}}
    </MemberDropdown>

    </a-button>
  </span>

</template>

<script>


  import RemoveButtonGroup from "~/components/cube/QueryBuilder/RemoveButtonGroup";
  import MemberDropdown from "~/components/cube/QueryBuilder/MemberDropdown";

  export default {
    name: "MemberGroup",
    layout: 'empty',
    auth: 'false',
    components: {MemberDropdown, RemoveButtonGroup},
    props: {
      itemProp: {
        type: Object,
        require: false,
        default: () => {
        }
      },
      list: {
        type: Array,
        require: false,
        default: () => []
      },
      membersProp: {
        type: Array,
        require: false,
        default: () => []
      },
      availableMembersProp: {
        type: Array,
        require: false,
        default: () => []
      },
      addMemberNameProp: {
        type: String,
        require: false,
        default: () => ""
      },
      updateMethods: {
        type: Object,
        require: false,
        default: () => {
        }
      },
    },
    data() {

      return {
        title: "demo",
        item: "",
      }
    },
    computed: {
      currentIndex() {
        return ''

      }
    },

    watch: {
      "title"() {
      },
      "itemProp": {
        immediate: true,
        handler(val) {
          if (val) {
            this.item = this.$common.deepCopy(val)

          }
        }
      },
    },

    async mounted() {

    },
    methods: {
      remove(m){
        this.updateMethods["remove"+this.addMemberNameProp+"s"](m.name)
      },
      update(oldM,newM){
        this.updateMethods["update"+this.addMemberNameProp+"s"](oldM.name,newM.name)

      },
      add(m){
        console.info("mmmmmmm--->",m)
       this.updateMethods["add"+this.addMemberNameProp+"s"](m.name)

      },
      async asyncMounted() {


      },
      async methodDemo() {

      },
      async dispatch() {
        this.$store.dispatch('modules/common/setCurrentIndex', 1)
      },
    }
  }
</script>

<style lang='scss'>

</style>
