// packages/cubejs-server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/components/QueryBuilder/SelectChartType.js
import React from 'react';
import * as PropTypes from 'prop-types';
import {
  Menu
} from 'antd';
import { Icon } from "@ant-design/compatible";
import ButtonDropdown from './ButtonDropdown';

const ChartTypes = [
  { name: 'line', title: 'Line', icon: 'line-chart' },
  { name: 'area', title: 'Area', icon: 'area-chart' },
  { name: 'bar', title: 'Bar', icon: 'bar-chart' },
  { name: 'pie', title: 'Pie', icon: 'pie-chart' },
  { name: 'table', title: 'Table', icon: 'table' },
  { name: 'number', title: 'Number', icon: 'info-circle' }
];

const SelectChartType = ({ chartType, updateChartType }) => {
  const menu = (
    <Menu>
      {ChartTypes.map(m => (
        <Menu.Item key={m.title} onClick={() => updateChartType(m.name)}>
          <Icon type={m.icon} />
          {m.title}
        </Menu.Item>
      ))}
    </Menu>
  );

  const foundChartType = ChartTypes.find(t => t.name === chartType);
  return (
    <ButtonDropdown overlay={menu} icon={<Icon type={foundChartType.icon}/>}>
      {foundChartType.title}
    </ButtonDropdown>
  );
};

SelectChartType.propTypes = {
  chartType: PropTypes.string.isRequired,
  updateChartType: PropTypes.func.isRequired
};

export default SelectChartType;

// packages/cubejs-server-core/dev/templates/packages/vue-antd-static/template/template/src/components/cube/QueryBuilder/SelectChartType.vue
<template>
  <a-dropdown>
      <a class="ant-dropdown-link" @click="e => e.preventDefault()" v-if="foundChartType">
        <a-icon :type="foundChartType.icon" />
        {{foundChartType.title}}
      </a>
      <a v-else>
        select
      </a>
    <a-menu slot="overlay">
      <a-menu-item v-for="item in ChartTypes" :key="item.title">
        <AIcon :type="item.icon"></AIcon>
        {{item.title}}
      </a-menu-item>
    </a-menu>
  </a-dropdown>
</template>

<script>
  export default {
    name: "SelectChartType",
    layout: 'empty',
    auth: 'false',
    components: {},
    props: {
      itemProp: {
        type: Object,
        require: false,
        default: () => {
        }
      },
      list: {
        type: Array,
        require: false,
        default: () => []
      },
      chartType: {
        type: String,
        require: false,
        default: () =>""
      },
      updateMethods: {
        type: Object,
        require: false,
        default: () => {
        }
      },
    },
    data() {
      return {
        title: "demo",
        item:"",
        ChartTypes: [
          {
            name: "line",
            title: "Line",
            icon: "line-chart"
          },
          {
            name: "area",
            title: "Area",
            icon: "area-chart"
          },
          {
            name: "bar",
            title: "Bar",
            icon: "bar-chart"
          },
          {
            name: "pie",
            title: "Pie",
            icon: "pie-chart"
          },
          {
            name: "table",
            title: "Table",
            icon: "table"
          },
          {
            name: "number",
            title: "Number",
            icon: "info-circle"
          }
        ],
      }
    },
    computed: {
      foundChartType(){
        const item =  this.ChartTypes.find(t => t.name === this.chartType);
        if(item){
          this.updateMethods['updateChartType'](item.name)
        }
        return item;
      },
      currentIndex() {
        return ''
      }
    },

    watch: {
      "title"() {},
      "itemProp":{
        immediate:true,
        handler(val){
          if(val){
            this.item = this.$common.deepCopy(val)
          }
        }
      },
    },

    async mounted() {
      setTimeout(()=>{
        this.updateMethods['updateChartType']("line")
      },200)
    },
    methods: {
      async asyncMounted() {

      },
      async methodDemo() {

      },
      async dispatch() {
        this.$store.dispatch('modules/common/setCurrentIndex', 1)
      },
    }
  }
</script>

<style lang='scss'>

</style>
