// examples/react-data-table/dashboard-app/src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { HashRouter as Router, Route } from 'react-router-dom';
import DashboardPage from './pages/DashboardPage';
import App from './App';
import "./index.css"

import createExampleWrapper from 'cube-example-wrapper'

const exampleDescription = {
  title: "React Data Table",
  text: `
    <p>This live demo shows a Material UI data table created with React and Cube.</p>
    <p>
      Follow 
      the <a href="https://dev.to/cubejs/react-data-table-with-material-ui-and-a-spark-of-joy-50o1">tutorial</a>
      or explore 
      the <a href="https://github.com/cube-js/cube.js/tree/master/examples/react-data-table">source code<a>
      to learn more.</p>
  `
}

createExampleWrapper(exampleDescription)

ReactDOM.render(
  <Router>
    <App>
      <Route key="index" exact path="/" component={DashboardPage} />
    </App>
  </Router>, // eslint-disable-next-line no-undef
  document.getElementById('root')
);

// examples/angular-dashboard-with-material-ui/dashboard-app/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import createExampleWrapper from "cube-example-wrapper"
const exampleDescription = {
  title: "Angular Dashboard with Material",
  text: `
  <p>This live demo shows a Material dashboard created with Angular and Cube.</p>
  <p>Follow the <a href="https://angular-dashboard.cube.dev/">tutorial</a> or explore the
    <a href="https://github.com/cube-js/cube.js/tree/master/examples/angular-dashboard-with-material-ui">source code</a>
    to learn more.
  </p>`
}

createExampleWrapper(exampleDescription)

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
