// examples/vue-dashboard/dashboard-app/src/App.vue
<template>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-4">
        <query-builder :cubejs-api="cubejsApi" :query="usersQuery">
          <template v-slot="{ loading, resultSet }">
            <Chart title="Total Users" type="number" :loading="loading" :result-set="resultSet"/>
          </template>
        </query-builder>
      </div>
      <div class="col-sm-4">
        <query-builder :cubejs-api="cubejsApi" :query="totalOrdersQuery">
          <template v-slot="{ loading, resultSet }">
            <Chart title="Total Orders" type="number" :loading="loading" :result-set="resultSet"/>
          </template>
        </query-builder>
      </div>
      <div class="col-sm-4">
        <query-builder :cubejs-api="cubejsApi" :query="shippedOrdersQuery">
          <template v-slot="{ loading, resultSet }">
            <Chart title="Shipped Users" type="number" :loading="loading" :result-set="resultSet"/>
          </template>
        </query-builder>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <query-builder :cubejs-api="cubejsApi" :query="lineQuery">
          <template v-slot="{ loading, resultSet }">
            <Chart
                    title="New Users Over Time"
                    type="line"
                    :loading="loading"
                    :result-set="resultSet"
            />
          </template>
        </query-builder>
      </div>
      <div class="col-sm-6">
        <query-builder :cubejs-api="cubejsApi" :query="barQuery">
          <template v-slot="{ loading, resultSet }">
            <Chart
                    title="Orders by Status Over time"
                    type="stackedBar"
                    :loading="loading"
                    :result-set="resultSet"
            />
          </template>
        </query-builder>
      </div>
    </div>
  </div>
</template>

<script>
  import cubejs from "@cubejs-client/core";
  import { QueryBuilder } from "@cubejs-client/vue";

  import Chart from "./components/Chart";

  const cubejsApi = cubejs(
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ2NjY4OTR9.0fdi5cuDZ2t3OSrPOMoc3B1_pwhnWj4ZmM3FHEX7Aus",
    { apiUrl: "https://ecom.cubecloudapp.dev/cubejs-api/v1" }
  );

  export default {
    name: "App",
    components: {
      Chart,
      QueryBuilder
    },
    data() {
      return {
        cubejsApi,
        usersQuery: { measures: ["Users.count"] },
        totalOrdersQuery: { measures: ["Orders.count"] },
        shippedOrdersQuery: {
          measures: ["Orders.count"],
          filters: [
            {
              dimension: "Orders.status",
              operator: "equals",
              values: ["shipped"]
            }
          ]
        },
        lineQuery: {
          measures: ["Users.count"],
          timeDimensions: [
            {
              dimension: "Users.createdAt",
              dateRange: ["2019-01-01", "2020-12-31"],
              granularity: "month"
            }
          ]
        },
        barQuery: {
          measures: ["Orders.count"],
          dimensions: ["Orders.status"],
          timeDimensions: [
            {
              dimension: "Orders.createdAt",
              dateRange: ["2019-01-01", "2020-12-31"],
              granularity: "month"
            }
          ]
        }
      };
    }
  };
</script>

<style>
  html {
    -webkit-font-smoothing: antialiased;
  }

  body {
    padding-top: 30px;
    padding-bottom: 30px;
    background: #f5f6f7;
  }
</style>

// examples/react-dashboard/dashboard-app/src/App.js
import React, { Component } from "react";
import { Container, Row, Col } from "reactstrap";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Legend,
  BarChart,
  Bar
} from "recharts";
import moment from "moment";
import numeral from "numeral";
import cubejs from "@cubejs-client/core";
import Chart from "./Chart.js";
import GithubCorner from 'react-github-corner';

const cubejsApi = cubejs(process.env.REACT_APP_CUBEJS_TOKEN, {
  apiUrl: process.env.REACT_APP_API_URL
});

const numberFormatter = item => numeral(item).format("0,0");
const dateFormatter = item => moment(item).format("MMM YY");

const renderSingleValue = (resultSet, key) => (
  <h1 height={300}>{numberFormatter(resultSet.chartPivot()[0][key])}</h1>
);

class App extends Component {
  render() {
    return (
      <Container fluid>
        <Row>
          <Col sm="4">
            <Chart
              cubejsApi={cubejsApi}
              title="Total Users"
              query={{ measures: ["Users.count"] }}
              render={resultSet => renderSingleValue(resultSet, "Users.count")}
            />
          </Col>
          <Col sm="4">
            <Chart
              cubejsApi={cubejsApi}
              title="Total Orders"
              query={{ measures: ["Orders.count"] }}
              render={resultSet => renderSingleValue(resultSet, "Orders.count")}
            />
          </Col>
          <Col sm="4">
            <Chart
              cubejsApi={cubejsApi}
              title="Shipped Orders"
              query={{
                measures: ["Orders.count"],
                filters: [
                  {
                    dimension: "Orders.status",
                    operator: "equals",
                    values: ["shipped"]
                  }
                ]
              }}
              render={resultSet => renderSingleValue(resultSet, "Orders.count")}
            />
          </Col>
        </Row>
        <br />
        <br />
        <Row>
          <Col sm="6">
            <Chart
              cubejsApi={cubejsApi}
              title="New Users Over Time"
              query={{
                measures: ["Users.count"],
                timeDimensions: [
                  {
                    dimension: "Users.createdAt",
                    dateRange: ["2017-01-01", "2018-12-31"],
                    granularity: "month"
                  }
                ]
              }}
              render={resultSet => (
                <ResponsiveContainer width="100%" height={300}>
                  <AreaChart data={resultSet.chartPivot()}>
                    <XAxis dataKey="category" tickFormatter={dateFormatter} />
                    <YAxis tickFormatter={numberFormatter} />
                    <Tooltip labelFormatter={dateFormatter} />
                    <Area
                      type="monotone"
                      dataKey="Users.count"
                      name="Users"
                      stroke="rgb(106, 110, 229)"
                      fill="rgba(106, 110, 229, .16)"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            />
          </Col>
          <Col sm="6">
            <Chart
              cubejsApi={cubejsApi}
              title="Orders by Status Over Time"
              query={{
                measures: ["Orders.count"],
                dimensions: ["Orders.status"],
                timeDimensions: [
                  {
                    dimension: "Orders.createdAt",
                    dateRange: ["2017-01-01", "2018-12-31"],
                    granularity: "month"
                  }
                ]
              }}
              render={resultSet => {
                return (
                  <ResponsiveContainer width="100%" height={300}>
                    <BarChart data={resultSet.chartPivot()}>
                      <XAxis tickFormatter={dateFormatter} dataKey="x" />
                      <YAxis tickFormatter={numberFormatter} />
                      <Bar
                        stackId="a"
                        dataKey="shipped, Orders.count"
                        name="Shipped"
                        fill="#7DB3FF"
                      />
                      <Bar
                        stackId="a"
                        dataKey="processing, Orders.count"
                        name="Processing"
                        fill="#49457B"
                      />
                      <Bar
                        stackId="a"
                        dataKey="completed, Orders.count"
                        name="Completed"
                        fill="#FF7C78"
                      />
                      <Legend />
                      <Tooltip />
                    </BarChart>
                  </ResponsiveContainer>
                );
              }}
            />
          </Col>
        </Row>
        <GithubCorner size={120} href="https://github.com/statsbotco/cube.js/tree/master/examples/react-dashboard" />
      </Container>
    );
  }
}

export default App;
